version: '3.8'

services:
  web:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=shelters_backend.settings
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,[::1],0.0.0.0
      - PORT=8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: gunicorn --bind :8000 --workers 2 shelters_backend.wsgi
